# Generated by Django 3.0 on 2023-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0003_auto_20181001_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectivequestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
