# Generated by Django 3.0 on 2023-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0004_subjectivequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectivequestion',
            old_name='desc',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='subjectivequestion',
            old_name='title',
            new_name='ques',
        ),
    ]
