# Generated by Django 3.0 on 2023-05-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0005_auto_20230520_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectivequestion',
            old_name='qus_id',
            new_name='qustion_id',
        ),
    ]
