# Generated by Django 3.0 on 2023-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0006_auto_20230520_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='ans1',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='ans',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
