# Generated by Django 3.0 on 2023-05-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0007_auto_20230520_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjectivequestion',
        ),
    ]
