# Generated by Django 3.0 on 2023-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0008_delete_subjectivequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion_id', models.IntegerField(unique=True)),
                ('ques', models.CharField(max_length=255)),
                ('ans', models.TextField(blank=True, max_length=30, null=True)),
                ('ans1', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
