# Generated by Django 3.0 on 2023-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_qus', '0009_subjectivequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='subQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('ans', models.TextField()),
                ('correct_option', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectiveQuestion',
        ),
    ]
